#! /usr/bin/env node
var optimist = require('optimist');
var trucker = require('./index');

var options = optimist
  .usage("Move CommonJS source files or directories without breaking your app.\nFixes requires in javascript and coffeescript files.\n$0 source [additional sources...] destination [flags]")
  .boolean('h')
  .alias('h', 'help')
  .describe('h', 'Show help')
  .boolean('i')
  .alias('i', 'info')
  .describe('i', 'Show dependencies of files passed')
  .boolean('n')
  .alias('n', 'dry-run')
  .describe('n', 'Print out changes to be made but don\'t change anything (try this first!)')
  .string('s')
  .alias('s', 'scope')
  .describe('s', 'Set top "scope" directory for scanning for dependencies (default: pwd)')
  .string('q')
  .alias('q', 'quiet')
  .describe('q', 'Suppress output');

var argv = options.argv;

if (argv.h || argv._.length < 2) {
  options.showHelp();
  process.exit();
}

var result = trucker(argv);
process.exit(result);
