name: Trucker
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: yarn install
      - run: yarn ci
